--
-- Insert from CSV-files
--

LOAD DATA LOCAL INFILE 'medlem.csv'
INTO TABLE medlem
CHARSET utf8
FIELDS
    TERMINATED BY ','
    ENCLOSED BY '"'
LINES
    TERMINATED BY '\n'
IGNORE 1 LINES
;

/* SELECT * FROM medlem; */

LOAD DATA LOCAL INFILE 'ras.csv'
INTO TABLE ras
CHARSET utf8
FIELDS
    TERMINATED BY ','
    ENCLOSED BY '"'
LINES
    TERMINATED BY '\n'
IGNORE 1 LINES
;

/* SELECT * FROM ras; */

LOAD DATA LOCAL INFILE 'medlem2hund.csv'
INTO TABLE medlem2hund
CHARSET utf8
FIELDS
    TERMINATED BY ','
    ENCLOSED BY '"'
LINES
    TERMINATED BY '\n'
IGNORE 1 LINES
;

/* SELECT * FROM medlem2hund; */

LOAD DATA LOCAL INFILE 'hund.csv'
INTO TABLE hund
CHARSET utf8
FIELDS
    TERMINATED BY ','
    ENCLOSED BY '"'
LINES
    TERMINATED BY '\n'
IGNORE 1 LINES
;

/* SELECT * FROM hund; */

SELECT * FROM memberInfo;